NetCore/OdeToFood/Models/EnumCuisineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
    public enum EnumCuisineType
    {
        None,
        Italian,
        French,
        German
    }
}

NetCore/OdeToFood/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        [Display(Name="Restaurant Name")]  // the lable displayed on front
        //[DisplayFormat]: useful for dispaly the date or time with format
        //[DataType(DataType.Text)]: set data type of input in front, it can use for password, email, etc.
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public EnumCuisineType Cuisine { get; set; }
    }
}

NetCore/OdeToFood/ViewModels/HomeIndexViewModel.cs
using OdeToFood.Models;
using System.Collections.Generic;

namespace OdeToFood.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string CurrentMessage { get; set; }
    }
}

NetCore/OdeToFood/ViewModels/RestaurantEditModel.cs
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewModels
{
    public class RestaurantEditModel
    {
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public EnumCuisineType Cuisine { get; set; }
    }
}

NetCore/OdeToFood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Controllers
{

    //[Route("controller")]
    [Route("[controller]/[action]")]
    public class AboutController
    {
        //[Route("action")]
        public string Phone() {
            return "111122223333";
        }

        //[Route("action")]
        public string Address() {
            return "Address";
        }
    }
}

NetCore/OdeToFood/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Controllers
{
    //[Authorize]
    public class HomeController : Controller
    {
        private IRestaurantData _resturantData;
        private IGreeter _greeter;

        public HomeController(IRestaurantData restaurantData, IGreeter greeter) {
            _resturantData = restaurantData;
            _greeter = greeter;
        }

        //[AllowAnonymous]
        public IActionResult Index() {
            //var model = new Restaurant { Id = 1, Name = "Zac" };
            //return new ObjectResult(model);
            //var model = _resturantData.GetAll();
            var model = new HomeIndexViewModel();
            model.Restaurants = _resturantData.GetAll();
            model.CurrentMessage = _greeter.GetMessage();
            return View(model);
        }

        public IActionResult Details(int id) {
            var model = _resturantData.Get(id);
            if (model == null) {
                //return NotFound();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create() {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]  // validate request token in case of cross-site request forgeries
        public IActionResult Create(RestaurantEditModel model) {
            // valid the post model
            if (ModelState.IsValid) {
                var newRestaurant = new Restaurant();
                newRestaurant.Name = model.Name;
                newRestaurant.Cuisine = model.Cuisine;
                newRestaurant = _resturantData.Add(newRestaurant);
                //return View("Details", newRestaurant);
                return RedirectToAction(nameof(Details), new { id = newRestaurant.Id, foo = "foo" });
            } else {
                return View();
            }
            
        }
    }
}

NetCore/OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantData;
        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public EditModel(IRestaurantData restaurantData) {
            _restaurantData = restaurantData;
        }
        public IActionResult OnGet(int id) {
            Restaurant = _restaurantData.Get(id);
            if(Restaurant == null) {
                return RedirectToAction("Index", "Home");
            }
            return Page();
        }

        public IActionResult OnPost() {
            if (ModelState.IsValid) {
                _restaurantData.Update(Restaurant);
                return RedirectToAction("Details","Home", new { id=Restaurant.Id });
            } else {
                return Page();
            }
        }
    }
}

NetCore/OdeToFood/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter) {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke() {
            var model = _greeter.GetMessage();
            return View("Default", model);
        }
    }
}

NetCore/OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using OdeToFood.Pages.Restaurants
@model EditModel

<h1>Edit @Model.Restaurant.Name</h1>
<form method="post">
    <input type="hidden" asp-for="Restaurant.Id"/>
    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>
    <div>
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine"
                asp-items="@Html.GetEnumSelectList<EnumCuisineType>()"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>

NetCore/OdeToFood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required: false); <!-- false: optional, true:required-->
    </footer>
</body>
</html>

NetCore/OdeToFood/Views/Home/Create.cshtml
@model Restaurant

@{
    ViewBag.Title = "Create page";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    //Set specific layout, or use global layout,
    //or set it as null means do not use layout
}

<h1>Create</h1>
<form method="post">
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="Cuisine"></label>
        <select asp-for="Cuisine"
                asp-items="@Html.GetEnumSelectList<EnumCuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>

NetCore/OdeToFood/Views/Home/Details.cshtml
@model Restaurant

@{
    ViewBag.Title = "Details page";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    //Set specific layout, or use global layout,
    //or set it as null means do not use layout
}

<h1>@Model.Name</h1>
<div>
    Id: @Model.Id
</div>
<div>
    Cuisine: @Model.Cuisine
</div>
<a asp-controller="Home" , asp-action="Index">Home</a>

NetCore/OdeToFood/Views/Home/Index.cshtml
@model HomeIndexViewModel

@{ 
    ViewBag.Title = "Index page";
    //Layout = "~/Views/Shared/_Layout.cshtml"; 
    //Set specific layout, or use global layout, 
    //or set it as null means do not use layout
}

<h1>@Model.CurrentMessage</h1>

@*Using partial view*@
@foreach(var restaurant in Model.Restaurants) {
    @Html.Partial("_Summary", restaurant);

}

<div>
    <a asp-action="Create" asp-controller="Home">Add Restaurant</a>
</div>

NetCore/OdeToFood/Views/Home/_Summary.cshtml
@model Restaurant

<section>
    <h3>@Model.Name</h3>
    <div>
        Cuisine: @Model.Cuisine
    </div>
    <div>
        <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

NetCore/OdeToFood/Views/Shared/Components/Greeter/Default.cshtml
@model string  
<div>
    @Model
</div>

NetCore/OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
              asp-fallback-href="~/node_modules/bootstrap/dist/css/bootstrap.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              rel="stylesheet" />
    </environment>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required: false); <!-- false: optional, true:required-->
        @*@await Component.InvokeAsync("Greeter");*@
        <vc:greeter></vc:greeter>  @*greeter is the name of view component*@
    </footer>
    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>

    </environment>
    
</body>
</html>